export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_EXITO = "SET_PRODUCTS_EXITO";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
